version: "3.9"

services:
  db:
    image: postgres:15
    container_name: blog_postgres
    restart: always
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: blog_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: blog_django
    restart: always
    command: gunicorn SimpleBlogPlatformProject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: "False"
      DJANGO_SETTINGS_MODULE: "SimpleBlogPlatformProject.settings"

      POSTGRES_DB: blog_db
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: blog_pass
      POSTGRES_HOST: db

  nginx:
    image: nginx:latest
    container_name: blog_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - web

  mutation:
    image: python:3.10
    working_dir: /app
    volumes:
      - .:/app
    command: >
      bash -c "
      pip install -r requirements.txt &&
      pip install mutmut pytest pytest-django &&
      mutmut run &&
      mutmut results
      "
    environment:
      MUTATION_TESTING: "1"


volumes:
  postgres_data:
