# Generated by Django 5.2.6 on 2025-10-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
