# Generated by Django 5.2.6 on 2025-11-22 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_userfriendrequests_user_friend_requests_userfriends_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="friend_requests",
            field=models.ManyToManyField(
                related_name="recipients",
                through="user.UserFriendRequests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="friends",
            field=models.ManyToManyField(
                through="user.UserFriends", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
