# Generated by Django 5.2.6 on 2025-12-06 09:46

from django.db import migrations, models

import user.models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_user_bio_delete_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=user.models.image_url
            ),
        ),
    ]
